name: myntra
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dots_indicator: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/bedsheet.webp
    - assets/both.webp
    - assets/coldskin.avif
    - assets/fashion.png
    - assets/fashionscale.jpeg
    - assets/foot.webp
    - assets/gofor.jpeg
    - assets/headphone.webp
    - assets/handbag.webp
    - assets/heels.jpg
    - assets/Home.jpeg
    - assets/jewel.webp
    - assets/kiara.webp
    - assets/kids.webp
    - assets/lamp.jpg
    - assets/logo.webp
    - assets/men.webp
    - assets/purse.webp
    - assets/product.jpeg
    - assets/scale.avif
    - assets/style.jpeg
    - assets/trolly.jpg
    - assets/watch.jpg
    - assets/whiteskin.webp
    - assets/women.jpg
    - assets/myntra.jpg
    - assets/fwd.jpg
    - assets/luxe.jpg
    - assets/bags.jpg
    - assets/girls.jpeg
    - assets/allen.jpeg
    - assets/bata.jpeg
    - assets/kurtasw.webp
    - assets/kurtiw.jpg
    - assets/vero.jpeg
    - assets/ninety.jpg
    - assets/twenty.jpg
    - assets/thirty.jpg
    - assets/fourty.jpg
    - assets/footcat.jpg
    - assets/kurtacat.jpg
    - assets/kurticat.jpg
    - assets/lipcat.webp
    - assets/moistcat.jpg
    - assets/shirtcat.jpg
    - assets/shirtcatm.jpg
    - assets/shirtcatm.jpg
    - assets/tshirtcatw.jpg
    - assets/watchcat.jpg
    - assets/bedcat.jpeg
    - assets/cascat.jpeg
    - assets/flipcat.jpeg
    - assets/jeanscat.jpeg
    - assets/kiddrcat.webp
    - assets/shampcat.jpeg
    - assets/shortcat.jpg
    - assets/sportcat.webp
    - assets/trackcat.avif
    - assets/trollycat.jpg
  
    
    
